// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmSmnj-i3dkQ2x5btS1ELq7iKNglYQXos',
    appId: '1:200367073891:web:d85d6cf1b51b2f7e70a656',
    messagingSenderId: '200367073891',
    projectId: 'lambda-820d2',
    authDomain: 'lambda-820d2.firebaseapp.com',
    storageBucket: 'lambda-820d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOY126MhqmLmUIZ4-HgBxgB7o37Al3SW0',
    appId: '1:200367073891:android:f130d2f5ad6a7b5c70a656',
    messagingSenderId: '200367073891',
    projectId: 'lambda-820d2',
    storageBucket: 'lambda-820d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-3XhvBAbZscnPmcmNsmYeOYts9v6v1KQ',
    appId: '1:200367073891:ios:e144cf103783863b70a656',
    messagingSenderId: '200367073891',
    projectId: 'lambda-820d2',
    storageBucket: 'lambda-820d2.appspot.com',
    iosBundleId: 'com.example.lambdaChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-3XhvBAbZscnPmcmNsmYeOYts9v6v1KQ',
    appId: '1:200367073891:ios:6b4f7fd3c38de54e70a656',
    messagingSenderId: '200367073891',
    projectId: 'lambda-820d2',
    storageBucket: 'lambda-820d2.appspot.com',
    iosBundleId: 'com.example.lambdaChat.RunnerTests',
  );
}
